// format is [[q1,a1],[q2,a2]]


const faqArr = [["What are my paying options","Lorem ipsum dolor sit amet, consectetur adipiscing   elit. Duis congue odio ac magna viverra, sit amet aliquet felis auctor. Etiam et arcu venenatis, dapibus erat non, pretium augue. Nulla nec nulla odio. Quisque dolor nibh, lacinia at sem quis, hendrerit tempus ligula. Praesent quis leo pretium lacus blandit faucibus nec a mi. Fusce et ultricies elit, porttitor euismod tortor. Nam id fringilla felis. Nulla tortor elit, vestibulum vitae ultricies in, sollicitudin ac enim. Donec finibus lacus sit amet orci tempus cursus."],

                ["What are your shipping Fees","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis congue odio ac magna viverra, sit amet aliquet felis auctor. Etiam et arcu venenatis, dapibus erat non, pretium augue. Nulla nec nulla odio. Quisque dolor nibh, lacinia at sem quis, hendrerit tempus ligula. Praesent quis leo pretium lacus blandit faucibus nec a mi. Fusce et ultricies elit, porttitor euismod tortor. Nam id fringilla felis. Nulla tortor elit, vestibulum vitae ultricies in, sollicitudin ac enim. Donec finibus lacus sit amet orci tempus cursus."],
                ["How do I know that my order has been shipped","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis congue odio ac magna viverra, sit amet aliquet felis auctor. Etiam et arcu venenatis, dapibus erat non, pretium augue. Nulla nec nulla odio. Quisque dolor nibh, lacinia at sem quis, hendrerit tempus ligula. Praesent quis leo pretium lacus blandit faucibus nec a mi. Fusce et ultricies elit, porttitor euismod tortor. Nam id fringilla felis. Nulla tortor elit, vestibulum vitae ultricies in, sollicitudin ac enim. Donec finibus lacus sit amet orci tempus cursus."],
                ["What's the status of my order? How do I track my order","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis congue odio ac magna viverra, sit amet aliquet felis auctor. Etiam et arcu venenatis, dapibus erat non, pretium augue. Nulla nec nulla odio. Quisque dolor nibh, lacinia at sem quis, hendrerit tempus ligula. Praesent quis leo pretium lacus blandit faucibus nec a mi. Fusce et ultricies elit, porttitor euismod tortor. Nam id fringilla felis. Nulla tortor elit, vestibulum vitae ultricies in, sollicitudin ac enim. Donec finibus lacus sit amet orci tempus cursus."],
                ["Can I change or cancel my order after it has been submitted","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis congue odio ac magna viverra, sit amet aliquet felis auctor. Etiam et arcu venenatis, dapibus erat non, pretium augue. Nulla nec nulla odio. Quisque dolor nibh, lacinia at sem quis, hendrerit tempus ligula. Praesent quis leo pretium lacus blandit faucibus nec a mi. Fusce et ultricies elit, porttitor euismod tortor. Nam id fringilla felis. Nulla tortor elit, vestibulum vitae ultricies in, sollicitudin ac enim. Donec finibus lacus sit amet orci tempus cursus."],
                ["How can I return or exchange an article","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis congue odio ac magna viverra, sit amet aliquet felis auctor. Etiam et arcu venenatis, dapibus erat non, pretium augue. Nulla nec nulla odio. Quisque dolor nibh, lacinia at sem quis, hendrerit tempus ligula. Praesent quis leo pretium lacus blandit faucibus nec a mi. Fusce et ultricies elit, porttitor euismod tortor. Nam id fringilla felis. Nulla tortor elit, vestibulum vitae ultricies in, sollicitudin ac enim. Donec finibus lacus sit amet orci tempus cursus."],
                ["What information about me is collected and stored, and how is that information used","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis congue odio ac magna viverra, sit amet aliquet felis auctor. Etiam et arcu venenatis, dapibus erat non, pretium augue. Nulla nec nulla odio. Quisque dolor nibh, lacinia at sem quis, hendrerit tempus ligula. Praesent quis leo pretium lacus blandit faucibus nec a mi. Fusce et ultricies elit, porttitor euismod tortor. Nam id fringilla felis. Nulla tortor elit, vestibulum vitae ultricies in, sollicitudin ac enim. Donec finibus lacus sit amet orci tempus cursus."],
                ["How will I be informed about changes reguarding the privacy policy","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis congue odio ac magna viverra, sit amet aliquet felis auctor. Etiam et arcu venenatis, dapibus erat non, pretium augue. Nulla nec nulla odio. Quisque dolor nibh, lacinia at sem quis, hendrerit tempus ligula. Praesent quis leo pretium lacus blandit faucibus nec a mi. Fusce et ultricies elit, porttitor euismod tortor. Nam id fringilla felis. Nulla tortor elit, vestibulum vitae ultricies in, sollicitudin ac enim. Donec finibus lacus sit amet orci tempus cursus."],
                ["How can I access, correct and update personal information","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis congue odio ac magna viverra, sit amet aliquet felis auctor. Etiam et arcu venenatis, dapibus erat non, pretium augue. Nulla nec nulla odio. Quisque dolor nibh, lacinia at sem quis, hendrerit tempus ligula. Praesent quis leo pretium lacus blandit faucibus nec a mi. Fusce et ultricies elit, porttitor euismod tortor. Nam id fringilla felis. Nulla tortor elit, vestibulum vitae ultricies in, sollicitudin ac enim. Donec finibus lacus sit amet orci tempus cursus."],
                ["What can I do if I forgot my password","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis congue odio ac magna viverra, sit amet aliquet felis auctor. Etiam et arcu venenatis, dapibus erat non, pretium augue. Nulla nec nulla odio. Quisque dolor nibh, lacinia at sem quis, hendrerit tempus ligula. Praesent quis leo pretium lacus blandit faucibus nec a mi. Fusce et ultricies elit, porttitor euismod tortor. Nam id fringilla felis. Nulla tortor elit, vestibulum vitae ultricies in, sollicitudin ac enim. Donec finibus lacus sit amet orci tempus cursus."], ]

export default faqArr